default_twitter: &default_twitter
  twitter_api_key: <%= ENV["TWITTER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_SECRET"] %>

development:
  secret_key_base: 3c5e8c3178785b42189eba3e87db60a8e55369951148a161f7c116bd8d64993fad2ff9e5287afed99965eebca99282fecea3b4d9586ce5213ebec64bfcdb35a2
  <<: *default_twitter

test:
  secret_key_base: e7413e472bdce83f421a998f52568de9e0c01c41ebd0642c776282b3f18b66882bc8a57ab430b9566c194f82b911772948d6b3ef4937aabf7758b662361f32ac
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
